rules = [
  OrganizeImports,
  DisableSyntax,
  LeakingImplicitClassVal,
  NoAutoTupling,
  NoValInForComprehension,
  ProcedureSyntax,
  RemoveUnused
]

DisableSyntax {
  noVars = false
  noThrows = false
  noNulls = false
  noReturns = false
  noWhileLoops = false
  noAsInstanceOf = false
  noIsInstanceOf = false
  noXml = true
  noDefaultArgs = false
  noFinalVal = true
  noFinalize = true
  noValPatterns = false
  noUniversalEquality = false
  regex = []
}

OrganizeImports {
  targetDialect = Scala3

  groups = [
    "re:javax?\\.",
    "scala.",
    "re:zio\\.(json|prelude|test)\\.",
    "zio.",
    "fish.genius.uml.",
    "fish.genius.",
    "*"
  ]

  removeUnused = true
  groupedImports = Merge
  groupExplicitlyImportedImplicitsSeparately = false
  importSelectorsOrder = SymbolsFirst
  importsOrder = SymbolsFirst
  coalesceToWildcardImportThreshold = 3
  expandRelative = true
  preset = INTELLIJ_2020_3
}

RemoveUnused {
  imports = true
  privates = true
  locals = true
  patternvars = true
}

NoAutoTupling.enabled = true
NoValInForComprehension.enabled = true
ProcedureSyntax.enabled = true
LeakingImplicitClassVal.enabled = true
