package fish.genius.uml.scene

import fish.genius.uml.dsl.archimate.{RelationshipType, ShapeType}

// The names the Blender builder knows its shapes and connectors by. Both matches are
// total, so a new ShapeType or RelationshipType does not compile until it has a shape.
object SceneNames:

  def of(kind: NodeKind): String = kind match
    case NodeKind.Element(shape) => of(shape)
    case NodeKind.Grouping       => "grouping"
    case NodeKind.AndJunction    => "and-junction"
    case NodeKind.OrJunction     => "or-junction"

  def of(shape: ShapeType): String = shape match
    case ShapeType.StrategyResource               => "resource"
    case ShapeType.StrategyCapability             => "capability"
    case ShapeType.StrategyValueStream            => "value-stream"
    case ShapeType.StrategyCourseOfAction         => "course-of-action"
    case ShapeType.BusinessActor                  => "business-actor"
    case ShapeType.BusinessRole                   => "business-role"
    case ShapeType.BusinessCollaboration          => "business-collaboration"
    case ShapeType.BusinessInterface              => "business-interface"
    case ShapeType.BusinessProcess                => "business-process"
    case ShapeType.BusinessFunction               => "business-function"
    case ShapeType.BusinessInteraction            => "business-interaction"
    case ShapeType.BusinessEvent                  => "business-event"
    case ShapeType.BusinessService                => "business-service"
    case ShapeType.BusinessObject                 => "business-object"
    case ShapeType.BusinessContract               => "contract"
    case ShapeType.BusinessRepresentation         => "representation"
    case ShapeType.BusinessProduct                => "product"
    case ShapeType.BusinessLocation               => "location"
    case ShapeType.ApplicationComponent           => "application-component"
    case ShapeType.ApplicationCollaboration       => "application-collaboration"
    case ShapeType.ApplicationInterface           => "application-interface"
    case ShapeType.ApplicationFunction            => "application-function"
    case ShapeType.ApplicationInteraction         => "application-interaction"
    case ShapeType.ApplicationProcess             => "application-process"
    case ShapeType.ApplicationEvent               => "application-event"
    case ShapeType.ApplicationService             => "application-service"
    case ShapeType.ApplicationDataObject          => "data-object"
    case ShapeType.TechnologyNode                 => "node"
    case ShapeType.TechnologyDevice               => "device"
    case ShapeType.TechnologySystemSoftware       => "system-software"
    case ShapeType.TechnologyCollaboration        => "technology-collaboration"
    case ShapeType.TechnologyInterface            => "technology-interface"
    case ShapeType.TechnologyPath                 => "path"
    case ShapeType.TechnologyCommunicationNetwork => "communication-network"
    case ShapeType.TechnologyFunction             => "technology-function"
    case ShapeType.TechnologyProcess              => "technology-process"
    case ShapeType.TechnologyInteraction          => "technology-interaction"
    case ShapeType.TechnologyEvent                => "technology-event"
    case ShapeType.TechnologyService              => "technology-service"
    case ShapeType.TechnologyArtifact             => "artifact"
    case ShapeType.PhysicalFacility               => "facility"
    case ShapeType.PhysicalEquipment              => "equipment"
    case ShapeType.PhysicalDistributionNetwork    => "distribution-network"
    case ShapeType.PhysicalMaterial               => "material"
    case ShapeType.MotivationStakeholder          => "stakeholder"
    case ShapeType.MotivationDriver               => "driver"
    case ShapeType.MotivationAssessment           => "assessment"
    case ShapeType.MotivationGoal                 => "goal"
    case ShapeType.MotivationOutcome              => "outcome"
    case ShapeType.MotivationPrinciple            => "principle"
    case ShapeType.MotivationRequirement          => "requirement"
    case ShapeType.MotivationConstraint           => "constraint"
    case ShapeType.MotivationMeaning              => "meaning"
    case ShapeType.MotivationValue                => "value"
    case ShapeType.ImplementationWorkPackage      => "work-package"
    case ShapeType.ImplementationDeliverable      => "deliverable"
    case ShapeType.ImplementationPlateau          => "plateau"
    case ShapeType.ImplementationEvent            => "implementation-event"
    case ShapeType.ImplementationGap              => "gap"

  def of(relationship: RelationshipType): String = relationship match
    case RelationshipType.Composition         => "composition"
    case RelationshipType.Aggregation         => "aggregation"
    case RelationshipType.Assignment          => "assignment"
    case RelationshipType.Realization         => "realization"
    case RelationshipType.Serving             => "serving"
    case RelationshipType.Access              => "access"
    case RelationshipType.ReadAccess          => "read-access"
    case RelationshipType.WriteAccess         => "write-access"
    case RelationshipType.ReadWriteAccess     => "read-write-access"
    case RelationshipType.Influence           => "influence"
    case RelationshipType.Association         => "association"
    case RelationshipType.DirectedAssociation => "directed-association"
    case RelationshipType.Triggering          => "triggering"
    case RelationshipType.Flow                => "flow"
    case RelationshipType.Specialization      => "specialization"

end SceneNames
